[project]
name = "rembi-mifa"
version = "0.1.2"
description = "Models for REMBI and MIFA metadata specifications for FAIR bioimaging data."
readme = "README.md"
license = "MIT"
authors = [{ name = "Chris Barnes", email = "chris.barnes@gerbi-gmb.de" }]
requires-python = ">=3.10"
dependencies = [
    "backports-strenum>=1.3.1;python_version<'3.11'",
    "email-validator>=2.3.0",
    "pydantic>=2.12.4",
]
keywords = ["rembi", "mifa", "fair", "bioimage", "metadata", "microscopy"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Pydantic",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[project.urls]
Repository = "https://github.com/clbarnes/rembi-mifa-py"

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.0",
    "mkdocstrings[python]>=0.30.1",
]
lint = ["mypy>=1.18.2", "ruff>=0.14.5"]
test = ["pytest>=9.0.1"]
dev = [
    "prek>=0.2.17",
    { include-group = "docs" },
    { include-group = "lint" },
    { include-group = "test" },
]
